/* ==========================================================================
   data.js — word bank, categories and achievement definitions
   Attaches to the single HEM namespace. Declares no global identifiers.
   Row format:
   [ english, hindiPronunciation, hindiMeaning, partOfSpeech, exampleSentence,
     hindiTranslation, synonyms, antonyms, usageTip, level(1-3), categoryKey ]
   ========================================================================== */
(function (HEM) {
  "use strict";

  var ROWS = [

    /* ---- daily ---- */
    ["Happy","हैपी","खुश","adjective","I am happy today.","मैं आज खुश हूँ।","glad, joyful, cheerful","sad, unhappy","am/is/are के साथ बोलें — I am happy.",1,"daily"],
    ["Sad","सैड","दुखी","adjective","She looks sad.","वह दुखी लग रही है।","unhappy, upset","happy, glad","looks/feels के साथ आम है।",1,"daily"],
    ["Hungry","हंग्री","भूखा","adjective","The child is hungry.","बच्चा भूखा है।","starving, famished","full","I am hungry बोलें, I have hunger नहीं।",1,"daily"],
    ["Thirsty","थर्स्टी","प्यासा","adjective","I am thirsty after the walk.","चलने के बाद मैं प्यासा हूँ।","parched, dry","quenched","पानी माँगते समय: I am thirsty.",1,"daily"],
    ["Tired","टायर्ड","थका हुआ","adjective","He is tired after work.","वह काम के बाद थका हुआ है।","exhausted, weary","fresh, energetic","tired of = किसी चीज़ से ऊब जाना।",1,"daily"],
    ["Sleep","स्लीप","सोना, नींद","verb","I sleep at ten every night.","मैं हर रात दस बजे सोता हूँ।","rest, nap","wake, awake","sleep = सोना, sleepy = नींद आना।",1,"daily"],
    ["Wake","वेक","जागना","verb","I wake up at six.","मैं छह बजे जागता हूँ।","rise, get up","sleep","हमेशा wake up बोलें।",1,"daily"],
    ["Morning","मॉर्निंग","सुबह","noun","I read the news in the morning.","मैं सुबह समाचार पढ़ता हूँ।","dawn, sunrise","evening, night","in the morning — at नहीं।",1,"daily"],
    ["Evening","ईवनिंग","शाम","noun","We walk in the evening.","हम शाम को टहलते हैं।","dusk, sundown","morning","in the evening सही रूप है।",1,"daily"],
    ["Night","नाइट","रात","noun","The village is quiet at night.","रात में गाँव शांत रहता है।","nighttime, darkness","day","at night — in नहीं।",1,"daily"],
    ["Water","वॉटर","पानी","noun","Please give me water.","कृपया मुझे पानी दीजिए।","liquid, H2O","","अगणनीय है — waters आमतौर पर नहीं।",1,"daily"],
    ["Food","फ़ूड","भोजन, खाना","noun","The food is very tasty.","खाना बहुत स्वादिष्ट है।","meal, diet","hunger","food अगणनीय है — foods कम प्रयोग।",1,"daily"],
    ["House","हाउस","घर, मकान","noun","Our house has two rooms.","हमारे घर में दो कमरे हैं।","home, residence","","house = इमारत, home = अपनापन।",1,"daily"],
    ["Family","फ़ैमिली","परिवार","noun","My family lives in a village.","मेरा परिवार गाँव में रहता है।","household, relatives","","एकवचन क्रिया लें — family is.",1,"daily"],
    ["Friend","फ़्रेंड","मित्र, दोस्त","noun","He is my best friend.","वह मेरा सबसे अच्छा दोस्त है।","companion, buddy","enemy","friend of mine भी सही है।",1,"daily"],
    ["Market","मार्केट","बाज़ार","noun","I go to the market on Sunday.","मैं रविवार को बाज़ार जाता हूँ।","bazaar, marketplace","","go to the market कहें।",1,"daily"],
    ["Money","मनी","पैसा, धन","noun","She saves money every month.","वह हर महीने पैसा बचाती है।","cash, funds","","अगणनीय — moneys नहीं।",1,"daily"],
    ["Clean","क्लीन","साफ़ करना, साफ़","verb","Clean your room daily.","अपना कमरा रोज़ साफ़ करो।","tidy, wash","dirty","विशेषण और क्रिया दोनों।",1,"daily"],
    ["Dirty","डर्टी","गंदा","adjective","The floor is dirty.","फ़र्श गंदा है।","filthy, unclean","clean","dirty water, dirty hands.",1,"daily"],
    ["Hot","हॉट","गर्म","adjective","The tea is very hot.","चाय बहुत गर्म है।","warm, boiling","cold","मौसम: It is hot today.",1,"daily"],
    ["Cold","कोल्ड","ठंडा, सर्दी","adjective","Winter nights are cold here.","यहाँ सर्दियों की रातें ठंडी होती हैं।","chilly, cool","hot","I have a cold = ज़ुकाम है।",1,"daily"],
    ["Busy","बिज़ी","व्यस्त","adjective","I am busy with my work.","मैं अपने काम में व्यस्त हूँ।","occupied, engaged","free, idle","busy with + काम।",1,"daily"],
    ["Free","फ़्री","खाली, मुफ़्त","adjective","Are you free this evening?","क्या आप आज शाम खाली हैं?","available, vacant","busy","free = खाली समय और मुफ़्त दोनों।",1,"daily"],
    ["Late","लेट","देर से","adjective","Do not come late to class.","कक्षा में देर से मत आओ।","delayed, tardy","early","be late for + कार्यक्रम।",1,"daily"],
    ["Early","अर्ली","जल्दी, समय से पहले","adjective","She reaches office early.","वह दफ़्तर जल्दी पहुँचती है।","prompt, ahead","late","early morning बहुत आम है।",1,"daily"],
    ["Buy","बाय","खरीदना","verb","I want to buy a book.","मैं एक किताब खरीदना चाहता हूँ।","purchase, get","sell","भूतकाल: bought.",1,"daily"],
    ["Sell","सेल","बेचना","verb","They sell vegetables here.","वे यहाँ सब्ज़ियाँ बेचते हैं।","trade, market","buy","भूतकाल: sold.",1,"daily"],
    ["Walk","वॉक","चलना, टहलना","verb","We walk two kilometres daily.","हम रोज़ दो किलोमीटर चलते हैं।","stroll, march","run","go for a walk = टहलने जाना।",1,"daily"],
    ["Cook","कुक","पकाना, रसोइया","verb","My mother cooks very well.","मेरी माँ बहुत अच्छा पकाती हैं।","prepare, bake","","cook = क्रिया और व्यक्ति दोनों।",1,"daily"],
    ["Rest","रेस्ट","आराम करना","verb","Take rest for an hour.","एक घंटे आराम करो।","relax, pause","work","take rest के बजाय rest भी सही है।",1,"daily"],

    /* ---- education ---- */
    ["Study","स्टडी","पढ़ाई करना","verb","I study English every night.","मैं हर रात अंग्रेज़ी पढ़ता हूँ।","learn, read","ignore","study for an exam बोलें।",1,"education"],
    ["Teacher","टीचर","शिक्षक","noun","Our teacher explains slowly.","हमारे शिक्षक धीरे-धीरे समझाते हैं।","instructor, tutor","student","teacher of English भी कह सकते हैं।",1,"education"],
    ["Student","स्टूडेंट","विद्यार्थी","noun","She is a hard-working student.","वह मेहनती विद्यार्थी है।","pupil, learner","teacher","स्कूल-कॉलेज दोनों के लिए।",1,"education"],
    ["School","स्कूल","विद्यालय","noun","The school opens at eight.","विद्यालय आठ बजे खुलता है।","academy, institute","","go to school में the नहीं लगता।",1,"education"],
    ["College","कॉलेज","महाविद्यालय","noun","He joined a college in the city.","उसने शहर के एक कॉलेज में दाख़िला लिया।","institute, university","","join a college / study in college.",1,"education"],
    ["Book","बुक","पुस्तक, बुक करना","noun","This book changed my thinking.","इस पुस्तक ने मेरी सोच बदल दी।","volume, text","","book a ticket = टिकट बुक करना।",1,"education"],
    ["Lesson","लेसन","पाठ, सबक","noun","Today's lesson is very useful.","आज का पाठ बहुत उपयोगी है।","chapter, class","","learn a lesson = सबक सीखना।",1,"education"],
    ["Homework","होमवर्क","गृहकार्य","noun","Finish your homework first.","पहले अपना गृहकार्य पूरा करो।","assignment, task","","अगणनीय — homeworks नहीं।",1,"education"],
    ["Exam","एग्ज़ाम","परीक्षा","noun","The exam starts next Monday.","परीक्षा अगले सोमवार से शुरू है।","test, examination","","give an exam नहीं, take an exam बोलें।",1,"education"],
    ["Result","रिज़ल्ट","परिणाम","noun","The result was better than expected.","परिणाम उम्मीद से बेहतर रहा।","outcome, score","cause","as a result = परिणामस्वरूप।",1,"education"],
    ["Practice","प्रैक्टिस","अभ्यास","noun","Daily practice makes you fluent.","रोज़ का अभ्यास आपको धाराप्रवाह बनाता है।","exercise, drill","theory","practice करना = practise (ब्रिटिश)।",1,"education"],
    ["Learn","लर्न","सीखना","verb","I learn ten new words daily.","मैं रोज़ दस नए शब्द सीखता हूँ।","study, grasp","forget","learn from mistakes = गलतियों से सीखना।",1,"education"],
    ["Knowledge","नॉलेज","ज्ञान","noun","Knowledge grows when shared.","बाँटने से ज्ञान बढ़ता है।","wisdom, learning","ignorance","अगणनीय — a knowledge नहीं।",2,"education"],
    ["Question","क्वेश्चन","प्रश्न","noun","May I ask a question?","क्या मैं एक प्रश्न पूछ सकता हूँ?","query, doubt","answer","ask a question — say नहीं।",1,"education"],
    ["Answer","आंसर","उत्तर","noun","Write the answer in short.","उत्तर संक्षेप में लिखिए।","reply, response","question","answer to a question.",1,"education"],
    ["Notebook","नोटबुक","कॉपी","noun","Keep a separate notebook for words.","शब्दों के लिए अलग कॉपी रखें।","copy, register","","भारत में copy बोला जाता है, अंग्रेज़ी में notebook।",1,"education"],
    ["Library","लाइब्रेरी","पुस्तकालय","noun","The library stays open till six.","पुस्तकालय छह बजे तक खुला रहता है।","reading room","","in the library = पुस्तकालय में।",1,"education"],
    ["Subject","सब्जेक्ट","विषय","noun","Mathematics is my favourite subject.","गणित मेरा पसंदीदा विषय है।","topic, discipline","","बात का विषय भी subject होता है।",1,"education"],
    ["Degree","डिग्री","उपाधि","noun","She has a degree in commerce.","उसके पास वाणिज्य में उपाधि है।","qualification, diploma","","a degree in + विषय।",2,"education"],
    ["Scholarship","स्कॉलरशिप","छात्रवृत्ति","noun","He won a scholarship for college.","उसे कॉलेज के लिए छात्रवृत्ति मिली।","grant, stipend","","win/get a scholarship.",2,"education"],
    ["Discipline","डिसिप्लिन","अनुशासन","noun","Discipline is stronger than talent.","अनुशासन प्रतिभा से अधिक शक्तिशाली है।","order, control","chaos","self-discipline = आत्म-अनुशासन।",2,"education"],
    ["Attendance","अटेंडेंस","उपस्थिति","noun","Your attendance is below seventy percent.","आपकी उपस्थिति सत्तर प्रतिशत से कम है।","presence","absence","mark attendance = हाज़िरी लगाना।",2,"education"],
    ["Revision","रिविज़न","दोहराव","noun","Revision before sleep helps memory.","सोने से पहले दोहराव याददाश्त बढ़ाता है।","review, recap","","do revision / revise कहें।",2,"education"],
    ["Syllabus","सिलेबस","पाठ्यक्रम","noun","Read the syllabus before you start.","शुरू करने से पहले पाठ्यक्रम पढ़ें।","curriculum, course","","बहुवचन: syllabuses.",2,"education"],

    /* ---- business ---- */
    ["Business","बिज़नेस","व्यापार","noun","He started a small business.","उसने एक छोटा व्यापार शुरू किया।","trade, company","","do business with = साथ व्यापार करना।",1,"business"],
    ["Profit","प्रॉफ़िट","लाभ, मुनाफ़ा","noun","The shop made a good profit.","दुकान ने अच्छा मुनाफ़ा कमाया।","gain, earnings","loss","make a profit — do नहीं।",2,"business"],
    ["Loss","लॉस","हानि, घाटा","noun","We faced a loss last year.","पिछले साल हमें घाटा हुआ।","deficit, damage","profit","at a loss = घाटे में।",2,"business"],
    ["Customer","कस्टमर","ग्राहक","noun","The customer is always important.","ग्राहक हमेशा महत्वपूर्ण होता है।","client, buyer","seller","दुकान के लिए customer, सेवा के लिए client।",1,"business"],
    ["Product","प्रोडक्ट","उत्पाद","noun","Our product is made in India.","हमारा उत्पाद भारत में बना है।","item, goods","","launch a product = उत्पाद उतारना।",1,"business"],
    ["Price","प्राइस","कीमत","noun","The price of rice has risen.","चावल की कीमत बढ़ गई है।","cost, rate","","price of + वस्तु।",1,"business"],
    ["Invest","इन्वेस्ट","निवेश करना","verb","Invest only what you can spare.","केवल उतना निवेश करें जितना बचा सकें।","fund, put in","withdraw","invest in + चीज़।",2,"business"],
    ["Budget","बजट","बजट, आय-व्यय","noun","Make a monthly budget for the family.","परिवार के लिए मासिक बजट बनाएँ।","plan, allowance","","on a budget = सीमित पैसे में।",2,"business"],
    ["Sale","सेल","बिक्री","noun","The sale ends on Sunday.","बिक्री रविवार को समाप्त होगी।","selling, discount","purchase","on sale = छूट पर।",1,"business"],
    ["Purchase","परचेज़","खरीद","noun","Keep the purchase bill safely.","खरीद का बिल सुरक्षित रखें।","buying, acquisition","sale","buy का औपचारिक रूप।",2,"business"],
    ["Supplier","सप्लायर","आपूर्तिकर्ता","noun","Our supplier delivers every week.","हमारा आपूर्तिकर्ता हर हफ़्ते माल देता है।","vendor, dealer","buyer","supplier of + सामान।",2,"business"],
    ["Contract","कॉन्ट्रैक्ट","अनुबंध","noun","Read the contract before signing.","हस्ताक्षर से पहले अनुबंध पढ़ें।","agreement, deal","","sign a contract.",2,"business"],
    ["Revenue","रेवेन्यू","आय, राजस्व","noun","Revenue doubled after the festival.","त्योहार के बाद आय दोगुनी हो गई।","income, turnover","expense","revenue = कुल आय, profit = शुद्ध लाभ।",3,"business"],
    ["Expense","एक्सपेंस","खर्च","noun","Travel expense is paid by the office.","यात्रा खर्च दफ़्तर देता है।","cost, spending","income","at the expense of = की कीमत पर।",2,"business"],
    ["Brand","ब्रांड","ब्रांड, पहचान","noun","Trust builds a strong brand.","भरोसा मज़बूत ब्रांड बनाता है।","label, name","","brand value = ब्रांड की साख।",2,"business"],
    ["Startup","स्टार्टअप","नया उद्यम","noun","His startup has five employees.","उसके नए उद्यम में पाँच कर्मचारी हैं।","new venture","","start-up भी लिखा जाता है।",2,"business"],
    ["Partner","पार्टनर","साझेदार","noun","She is my business partner.","वह मेरी व्यापारिक साझेदार है।","associate, ally","rival","partner with = साझेदारी करना।",2,"business"],
    ["Growth","ग्रोथ","वृद्धि","noun","The company shows steady growth.","कंपनी में लगातार वृद्धि दिख रही है।","rise, increase","decline","growth in / growth of दोनों।",2,"business"],
    ["Strategy","स्ट्रैटेजी","रणनीति","noun","We need a better sales strategy.","हमें बेहतर बिक्री रणनीति चाहिए।","plan, approach","","बहुवचन: strategies.",3,"business"],
    ["Negotiate","निगोशिएट","मोल-भाव करना","verb","Learn to negotiate politely.","विनम्रता से मोल-भाव करना सीखें।","bargain, discuss","accept","negotiate with + व्यक्ति।",3,"business"],
    ["Client","क्लाइंट","मुवक्किल, ग्राहक","noun","The client approved our design.","ग्राहक ने हमारा डिज़ाइन स्वीकार किया।","customer, patron","","सेवा-आधारित काम में client कहते हैं।",2,"business"],
    ["Invoice","इनवॉइस","बीजक, बिल","noun","Send the invoice by email.","बिल ईमेल से भेजें।","bill, receipt","","raise an invoice = बिल बनाना।",3,"business"],
    ["Competition","कॉम्पिटीशन","प्रतिस्पर्धा","noun","Competition improves quality.","प्रतिस्पर्धा गुणवत्ता सुधारती है।","rivalry, contest","cooperation","competitor = प्रतिस्पर्धी व्यक्ति।",2,"business"],
    ["Marketing","मार्केटिंग","विपणन, प्रचार","noun","Good marketing brings new customers.","अच्छा विपणन नए ग्राहक लाता है।","promotion, publicity","","marketing = बेचने का प्रचार।",2,"business"],

    /* ---- tech ---- */
    ["Computer","कंप्यूटर","संगणक","noun","Every office needs a computer.","हर दफ़्तर को कंप्यूटर चाहिए।","PC, machine","","on the computer = कंप्यूटर पर।",1,"tech"],
    ["Mobile","मोबाइल","चलायमान, मोबाइल फ़ोन","noun","My mobile battery is low.","मेरे मोबाइल की बैटरी कम है।","cellphone, handset","","अमेरिका में cell phone कहते हैं।",1,"tech"],
    ["Internet","इंटरनेट","अंतरजाल","noun","The internet connects the world.","इंटरनेट दुनिया को जोड़ता है।","web, net","","हमेशा the internet।",1,"tech"],
    ["Software","सॉफ़्टवेयर","सॉफ़्टवेयर","noun","Update the software regularly.","सॉफ़्टवेयर नियमित रूप से अपडेट करें।","program, application","hardware","अगणनीय — softwares गलत है।",2,"tech"],
    ["Hardware","हार्डवेयर","यंत्र सामग्री","noun","The hardware is old but working.","यंत्र पुराने हैं पर काम कर रहे हैं।","equipment, machinery","software","अगणनीय संज्ञा।",2,"tech"],
    ["Website","वेबसाइट","वेबसाइट","noun","Our website loads very fast.","हमारी वेबसाइट बहुत तेज़ खुलती है।","site, webpage","","visit a website.",1,"tech"],
    ["Password","पासवर्ड","गुप्त शब्द","noun","Never share your password.","अपना पासवर्ड कभी साझा न करें।","code, PIN","","strong password रखें।",1,"tech"],
    ["Download","डाउनलोड","उतारना","verb","Download the file before travel.","यात्रा से पहले फ़ाइल डाउनलोड करें।","save, transfer","upload","download from + स्रोत।",1,"tech"],
    ["Upload","अपलोड","चढ़ाना","verb","Upload your photo here.","अपनी तस्वीर यहाँ अपलोड करें।","post, send","download","upload to + जगह।",1,"tech"],
    ["Screen","स्क्रीन","पर्दा","noun","Clean the screen with a soft cloth.","स्क्रीन को मुलायम कपड़े से साफ़ करें।","display, monitor","","screen time = स्क्रीन पर बिताया समय।",1,"tech"],
    ["Keyboard","कीबोर्ड","कुंजीपटल","noun","This keyboard has Hindi letters.","इस कीबोर्ड पर हिंदी अक्षर हैं।","keypad","","type on a keyboard.",1,"tech"],
    ["Battery","बैटरी","बैटरी","noun","The battery lasts two days.","बैटरी दो दिन चलती है।","cell, power pack","","battery is low / charged.",1,"tech"],
    ["Network","नेटवर्क","संजाल","noun","The network is weak in my village.","मेरे गाँव में नेटवर्क कमज़ोर है।","connection, system","","network problem = नेटवर्क की दिक्कत।",2,"tech"],
    ["Data","डेटा","आँकड़े","noun","Mobile data is cheap in India.","भारत में मोबाइल डेटा सस्ता है।","information, figures","","अगणनीय की तरह प्रयोग होता है।",2,"tech"],
    ["File","फ़ाइल","संचिका","noun","Save the file before closing.","बंद करने से पहले फ़ाइल सहेजें।","document, record","","open/save/delete a file.",1,"tech"],
    ["Update","अपडेट","नवीनीकरण","noun","A new update is available.","एक नया अपडेट उपलब्ध है।","upgrade, revision","","update करना = क्रिया भी।",2,"tech"],
    ["Device","डिवाइस","उपकरण","noun","This device works without internet.","यह उपकरण बिना इंटरनेट चलता है।","gadget, machine","","smart device = स्मार्ट उपकरण।",2,"tech"],
    ["Application","एप्लिकेशन","अनुप्रयोग, आवेदन","noun","Install the application from the store.","स्टोर से एप्लिकेशन इंस्टॉल करें।","app, program","","नौकरी के लिए application = आवेदन।",2,"tech"],
    ["Browser","ब्राउज़र","ब्राउज़र","noun","Open the link in another browser.","लिंक दूसरे ब्राउज़र में खोलें।","web client","","Chrome, Firefox आदि browser हैं।",2,"tech"],
    ["Server","सर्वर","सर्वर","noun","The server is down for repair.","सर्वर मरम्मत के लिए बंद है।","host, mainframe","client","server down = सेवा बंद।",3,"tech"],
    ["Storage","स्टोरेज","भंडारण","noun","My phone storage is full.","मेरे फ़ोन का भंडारण भर गया है।","memory, space","","cloud storage = ऑनलाइन भंडारण।",2,"tech"],
    ["Charger","चार्जर","आवेशक","noun","I forgot my charger at home.","मैं अपना चार्जर घर भूल गया।","adapter","","plug in the charger.",1,"tech"],
    ["Signal","सिग्नल","संकेत","noun","There is no signal on the hill.","पहाड़ पर कोई सिग्नल नहीं है।","sign, indication","","traffic signal भी यही शब्द।",1,"tech"],
    ["Digital","डिजिटल","अंकीय","adjective","India is going digital fast.","भारत तेज़ी से डिजिटल हो रहा है।","electronic, online","analog","digital payment = ऑनलाइन भुगतान।",2,"tech"],

    /* ---- ai ---- */
    ["Artificial","आर्टिफ़िशियल","कृत्रिम","adjective","This is artificial light, not sunlight.","यह कृत्रिम प्रकाश है, सूरज की रोशनी नहीं।","man-made, synthetic","natural","artificial intelligence = कृत्रिम बुद्धिमत्ता।",2,"ai"],
    ["Intelligence","इंटेलिजेंस","बुद्धिमत्ता","noun","Intelligence grows with practice.","अभ्यास से बुद्धिमत्ता बढ़ती है।","cleverness, intellect","stupidity","अगणनीय संज्ञा है।",2,"ai"],
    ["Robot","रोबोट","यंत्रमानव","noun","A robot packs the boxes here.","यहाँ एक रोबोट डिब्बे पैक करता है।","machine, automaton","human","robotic = रोबोट जैसा।",1,"ai"],
    ["Machine","मशीन","यंत्र","noun","This machine learns from examples.","यह यंत्र उदाहरणों से सीखता है।","device, engine","","machine learning = मशीन का सीखना।",1,"ai"],
    ["Algorithm","एल्गोरिदम","कलन विधि","noun","The algorithm sorts names quickly.","यह कलन विधि नामों को तेज़ी से क्रम में लगाती है।","procedure, method","","step-by-step नियमों का समूह।",3,"ai"],
    ["Automation","ऑटोमेशन","स्वचालन","noun","Automation saves hours of work.","स्वचालन घंटों का काम बचाता है।","mechanisation","manual work","automate = स्वचालित करना।",3,"ai"],
    ["Chatbot","चैटबॉट","बातचीत करने वाला प्रोग्राम","noun","A chatbot answers customer questions.","चैटबॉट ग्राहकों के प्रश्नों का उत्तर देता है।","virtual agent","","chat + robot से बना शब्द।",2,"ai"],
    ["Model","मॉडल","प्रतिरूप","noun","The model predicts tomorrow's demand.","यह प्रतिरूप कल की माँग बताता है।","system, framework","","AI में model = प्रशिक्षित प्रोग्राम।",2,"ai"],
    ["Training","ट्रेनिंग","प्रशिक्षण","noun","Training makes the model accurate.","प्रशिक्षण मॉडल को सटीक बनाता है।","coaching, teaching","","train = प्रशिक्षित करना।",2,"ai"],
    ["Prediction","प्रिडिक्शन","भविष्यवाणी","noun","The prediction was almost correct.","भविष्यवाणी लगभग सही थी।","forecast, guess","","predict = अनुमान लगाना।",2,"ai"],
    ["Neural","न्यूरल","तंत्रिका संबंधी","adjective","A neural network copies the brain.","तंत्रिका जाल मस्तिष्क की नकल करता है।","nerve-related","","neural network एक साथ बोलें।",3,"ai"],
    ["Dataset","डेटासेट","आँकड़ा समूह","noun","A clean dataset gives better results.","स्वच्छ आँकड़ा समूह बेहतर परिणाम देता है।","data collection","","data + set से बना।",3,"ai"],
    ["Prompt","प्रॉम्प्ट","निर्देश","noun","Write a clear prompt for the AI.","एआई के लिए स्पष्ट निर्देश लिखें।","instruction, cue","","prompt = तुरंत भी होता है।",2,"ai"],
    ["Accuracy","एक्युरेसी","सटीकता","noun","The accuracy improved after training.","प्रशिक्षण के बाद सटीकता बढ़ गई।","precision, exactness","error","accurate = सटीक।",2,"ai"],
    ["Virtual","वर्चुअल","आभासी","adjective","We had a virtual meeting.","हमने आभासी बैठक की।","online, simulated","physical, real","virtual class = ऑनलाइन कक्षा।",2,"ai"],
    ["Assistant","असिस्टेंट","सहायक","noun","A voice assistant sets my alarm.","आवाज़ सहायक मेरा अलार्म लगाता है।","helper, aide","","assist = सहायता करना।",1,"ai"],
    ["Recognition","रेकग्निशन","पहचान","noun","Face recognition unlocks the phone.","चेहरा पहचान फ़ोन खोलती है।","identification","","recognise = पहचानना।",3,"ai"],
    ["Generate","जेनरेट","उत्पन्न करना","verb","AI can generate images from text.","एआई पाठ से चित्र उत्पन्न कर सकता है।","create, produce","destroy","generative = उत्पन्न करने वाला।",2,"ai"],
    ["Bias","बायस","पक्षपात","noun","Bias in data creates unfair results.","आँकड़ों में पक्षपात अनुचित परिणाम देता है।","prejudice, partiality","fairness","biased = पक्षपाती।",3,"ai"],
    ["Ethics","एथिक्स","नैतिकता","noun","AI must follow strong ethics.","एआई को मज़बूत नैतिकता माननी चाहिए।","morals, values","","बहुवचन रूप में ही चलता है।",3,"ai"],

    /* ---- comm ---- */
    ["Speak","स्पीक","बोलना","verb","Speak slowly and clearly.","धीरे और स्पष्ट बोलिए।","talk, say","listen","speak to / speak with somebody.",1,"comm"],
    ["Listen","लिसन","ध्यान से सुनना","verb","Listen to the teacher carefully.","शिक्षक को ध्यान से सुनिए।","hear, attend","ignore","हमेशा listen to बोलें।",1,"comm"],
    ["Explain","एक्सप्लेन","समझाना","verb","Please explain it in Hindi.","कृपया इसे हिंदी में समझाइए।","clarify, describe","confuse","explain me गलत है — explain to me सही।",2,"comm"],
    ["Discuss","डिस्कस","चर्चा करना","verb","Let us discuss the plan today.","आइए आज योजना पर चर्चा करें।","talk over, debate","","discuss about गलत है — सिर्फ़ discuss.",2,"comm"],
    ["Message","मैसेज","संदेश","noun","I sent you a message yesterday.","मैंने कल आपको संदेश भेजा था।","note, text","","send/get a message.",1,"comm"],
    ["Call","कॉल","बुलाना, फ़ोन करना","verb","Call me after eight.","आठ बजे के बाद मुझे फ़ोन करना।","phone, ring","","call me — call to me नहीं।",1,"comm"],
    ["Reply","रिप्लाई","उत्तर देना","verb","Reply to the email today.","आज ईमेल का उत्तर दीजिए।","respond, answer","ask","reply to + चीज़।",1,"comm"],
    ["Request","रिक्वेस्ट","अनुरोध","noun","I have a small request.","मेरा एक छोटा-सा अनुरोध है।","appeal, plea","order","make a request.",2,"comm"],
    ["Suggest","सजेस्ट","सुझाव देना","verb","I suggest starting with easy words.","मेरा सुझाव है कि आसान शब्दों से शुरू करें।","advise, recommend","","suggest me गलत — suggest to me सही।",2,"comm"],
    ["Apologize","अपोलोजाइज़","क्षमा माँगना","verb","He apologized for the delay.","उसने देरी के लिए क्षमा माँगी।","say sorry, regret","","apologize for + गलती।",2,"comm"],
    ["Greet","ग्रीट","अभिवादन करना","verb","Greet everyone with a smile.","सबका मुस्कान से अभिवादन कीजिए।","welcome, salute","ignore","greeting = अभिवादन।",1,"comm"],
    ["Introduce","इंट्रोड्यूस","परिचय कराना","verb","Let me introduce my friend.","मैं अपने मित्र का परिचय कराता हूँ।","present, acquaint","","introduce yourself = अपना परिचय दें।",2,"comm"],
    ["Conversation","कन्वर्सेशन","बातचीत","noun","We had a long conversation.","हमने लंबी बातचीत की।","talk, chat","silence","have a conversation with.",2,"comm"],
    ["Language","लैंग्वेज","भाषा","noun","English is a global language.","अंग्रेज़ी एक वैश्विक भाषा है।","tongue, speech","","mother tongue = मातृभाषा।",1,"comm"],
    ["Fluent","फ़्लुएंट","धाराप्रवाह","adjective","She is fluent in three languages.","वह तीन भाषाओं में धाराप्रवाह है।","smooth, articulate","hesitant","fluent in + भाषा।",2,"comm"],
    ["Polite","पोलाइट","विनम्र","adjective","Always use polite words.","हमेशा विनम्र शब्दों का प्रयोग करें।","courteous, respectful","rude","polite request = विनम्र अनुरोध।",1,"comm"],
    ["Clear","क्लियर","स्पष्ट","adjective","Your voice is not clear.","आपकी आवाज़ स्पष्ट नहीं है।","plain, obvious","unclear, vague","make it clear = स्पष्ट करना।",1,"comm"],
    ["Repeat","रिपीट","दोहराना","verb","Could you repeat that, please?","क्या आप उसे दोहरा सकते हैं?","say again, echo","","repeat again कहना दोहराव है।",1,"comm"],
    ["Understand","अंडरस्टैंड","समझना","verb","I understand a little English.","मैं थोड़ी अंग्रेज़ी समझता हूँ।","grasp, follow","misunderstand","भूतकाल: understood.",1,"comm"],
    ["Express","एक्सप्रेस","व्यक्त करना","verb","Express your feelings without fear.","अपनी भावनाएँ बिना डर के व्यक्त करें।","convey, state","suppress","express yourself = अपनी बात कहना।",2,"comm"],
    ["Inform","इनफ़ॉर्म","सूचित करना","verb","Inform the office before leaving.","जाने से पहले दफ़्तर को सूचित करें।","notify, tell","hide","inform somebody about something.",2,"comm"],
    ["Confirm","कन्फ़र्म","पुष्टि करना","verb","Please confirm your booking.","कृपया अपनी बुकिंग की पुष्टि करें।","verify, approve","deny","confirmation = पुष्टि।",2,"comm"],
    ["Feedback","फ़ीडबैक","प्रतिक्रिया","noun","Your feedback helps us improve.","आपकी प्रतिक्रिया हमें सुधरने में मदद करती है।","response, opinion","","अगणनीय — feedbacks नहीं।",2,"comm"],
    ["Silence","साइलेंस","मौन","noun","Silence is also an answer.","मौन भी एक उत्तर है।","quiet, stillness","noise","keep silence = चुप रहना।",2,"comm"],

    /* ---- health ---- */
    ["Health","हेल्थ","स्वास्थ्य","noun","Health is real wealth.","स्वास्थ्य ही असली धन है।","wellbeing, fitness","illness","अगणनीय संज्ञा।",1,"health"],
    ["Doctor","डॉक्टर","चिकित्सक","noun","Meet a doctor if the fever stays.","बुखार बना रहे तो चिकित्सक से मिलें।","physician, medic","patient","see a doctor = डॉक्टर को दिखाना।",1,"health"],
    ["Medicine","मेडिसिन","दवा","noun","Take this medicine after food.","यह दवा खाने के बाद लें।","drug, remedy","","take medicine — eat नहीं।",1,"health"],
    ["Fever","फ़ीवर","बुखार","noun","He has a high fever.","उसे तेज़ बुखार है।","temperature","","have a fever बोलें।",1,"health"],
    ["Pain","पेन","दर्द","noun","I feel pain in my back.","मुझे पीठ में दर्द है।","ache, hurt","comfort","pain in + शरीर का अंग।",1,"health"],
    ["Exercise","एक्सरसाइज़","व्यायाम","noun","Daily exercise keeps you strong.","रोज़ का व्यायाम आपको मज़बूत रखता है।","workout, activity","rest","do exercise / exercise daily.",1,"health"],
    ["Diet","डाइट","आहार","noun","A balanced diet prevents disease.","संतुलित आहार बीमारी से बचाता है।","food plan, nutrition","","on a diet = परहेज़ पर।",2,"health"],
    ["Hospital","हॉस्पिटल","अस्पताल","noun","The hospital is two kilometres away.","अस्पताल दो किलोमीटर दूर है।","clinic, infirmary","","in hospital = भर्ती होना।",1,"health"],
    ["Nurse","नर्स","परिचारिका","noun","The nurse checked my pulse.","नर्स ने मेरी नब्ज़ देखी।","caregiver, attendant","","nursing = देखभाल का कार्य।",1,"health"],
    ["Injury","इंजरी","चोट","noun","The injury needs three stitches.","चोट में तीन टाँके चाहिए।","wound, harm","","injured = घायल।",2,"health"],
    ["Treatment","ट्रीटमेंट","उपचार","noun","The treatment lasted one month.","उपचार एक महीने चला।","cure, therapy","","under treatment = इलाज चल रहा है।",2,"health"],
    ["Healthy","हेल्दी","स्वस्थ","adjective","She stays healthy by walking.","वह टहलकर स्वस्थ रहती है।","fit, well","sick, unhealthy","healthy food = पौष्टिक भोजन।",1,"health"],
    ["Weak","वीक","कमज़ोर","adjective","He feels weak after the illness.","बीमारी के बाद वह कमज़ोर महसूस करता है।","feeble, frail","strong","weak और week का उच्चारण एक जैसा।",1,"health"],
    ["Fitness","फ़िटनेस","शारीरिक क्षमता","noun","Fitness improves with routine.","नियमितता से शारीरिक क्षमता बढ़ती है।","strength, stamina","weakness","fitness level = शरीर की क्षमता।",2,"health"],
    ["Stress","स्ट्रेस","तनाव","noun","Too much stress harms sleep.","अधिक तनाव नींद को नुकसान पहुँचाता है।","tension, pressure","calm","under stress = तनाव में।",2,"health"],
    ["Mind","माइंड","मन, मस्तिष्क","noun","A calm mind solves problems.","शांत मन समस्याएँ हल करता है।","brain, thought","body","never mind = कोई बात नहीं।",1,"health"],
    ["Breath","ब्रेथ","साँस","noun","Take a deep breath and relax.","गहरी साँस लीजिए और शांत होइए।","air, inhalation","","breath संज्ञा, breathe क्रिया।",2,"health"],
    ["Blood","ब्लड","रक्त","noun","Blood donation saves lives.","रक्तदान जीवन बचाता है।","","","blood pressure = रक्तचाप।",1,"health"],
    ["Cough","कॉफ़","खाँसी","noun","This syrup stops a dry cough.","यह सिरप सूखी खाँसी रोकता है।","","","उच्चारण कॉफ़ है, काउ नहीं।",1,"health"],
    ["Immunity","इम्युनिटी","रोग प्रतिरोधक क्षमता","noun","Good sleep builds immunity.","अच्छी नींद रोग प्रतिरोधक क्षमता बढ़ाती है।","resistance, defence","","immune = प्रतिरक्षित।",3,"health"],
    ["Nutrition","न्यूट्रिशन","पोषण","noun","Children need proper nutrition.","बच्चों को उचित पोषण चाहिए।","nourishment, diet","","nutritious = पौष्टिक।",2,"health"],
    ["Recover","रिकवर","स्वस्थ होना","verb","He recovered within a week.","वह एक हफ़्ते में स्वस्थ हो गया।","heal, improve","worsen","recover from + बीमारी।",2,"health"],
    ["Checkup","चेकअप","जाँच","noun","Get a checkup once a year.","साल में एक बार जाँच कराएँ।","examination, test","","health checkup कहा जाता है।",1,"health"],
    ["Hygiene","हाइजीन","स्वच्छता","noun","Hygiene prevents many diseases.","स्वच्छता कई बीमारियों से बचाती है।","cleanliness, sanitation","dirtiness","उच्चारण हाइजीन है।",3,"health"],

    /* ---- travel ---- */
    ["Travel","ट्रैवल","यात्रा करना","verb","I travel by bus every week.","मैं हर हफ़्ते बस से यात्रा करता हूँ।","journey, tour","stay","travel by + वाहन।",1,"travel"],
    ["Journey","जर्नी","सफ़र","noun","The journey took six hours.","सफ़र में छह घंटे लगे।","trip, voyage","","journey = एक तरफ़ का सफ़र।",1,"travel"],
    ["Ticket","टिकट","टिकट","noun","Book the ticket in advance.","टिकट पहले से बुक करें।","pass, coupon","","book/buy a ticket.",1,"travel"],
    ["Station","स्टेशन","स्टेशन","noun","The train reaches the station at nine.","गाड़ी नौ बजे स्टेशन पहुँचती है।","depot, terminal","","railway station / bus station.",1,"travel"],
    ["Airport","एयरपोर्ट","हवाई अड्डा","noun","Reach the airport two hours early.","हवाई अड्डे दो घंटे पहले पहुँचें।","airfield","","at the airport कहें।",1,"travel"],
    ["Luggage","लगेज","सामान","noun","Keep your luggage with you.","अपना सामान अपने पास रखें।","baggage, bags","","अगणनीय — luggages नहीं।",2,"travel"],
    ["Hotel","होटल","होटल","noun","The hotel is near the temple.","होटल मंदिर के पास है।","lodge, inn","","stay at a hotel.",1,"travel"],
    ["Booking","बुकिंग","आरक्षण","noun","My booking is confirmed.","मेरा आरक्षण पक्का हो गया है।","reservation","cancellation","booking confirmed / cancelled.",1,"travel"],
    ["Passport","पासपोर्ट","पासपोर्ट","noun","Keep your passport safe abroad.","विदेश में पासपोर्ट सुरक्षित रखें।","travel document","","apply for a passport.",2,"travel"],
    ["Map","मैप","नक्शा","noun","Open the map on your phone.","अपने फ़ोन पर नक्शा खोलिए।","chart, atlas","","on the map = नक्शे पर।",1,"travel"],
    ["Road","रोड","सड़क","noun","The road to the village is narrow.","गाँव की सड़क सँकरी है।","street, path","","on the road = सफ़र में।",1,"travel"],
    ["Village","विलेज","गाँव","noun","My village has clean air.","मेरे गाँव की हवा साफ़ है।","hamlet","city","in a village रहते हैं।",1,"travel"],
    ["City","सिटी","शहर","noun","The city never sleeps.","शहर कभी सोता नहीं।","town, metro","village","in the city कहें।",1,"travel"],
    ["Distance","डिस्टेंस","दूरी","noun","The distance is only ten kilometres.","दूरी केवल दस किलोमीटर है।","gap, span","","distance between A and B.",2,"travel"],
    ["Arrive","अराइव","पहुँचना","verb","We arrive at noon.","हम दोपहर को पहुँचते हैं।","reach, land","depart, leave","arrive at (जगह), arrive in (शहर)।",2,"travel"],
    ["Depart","डिपार्ट","प्रस्थान करना","verb","The bus departs at five sharp.","बस ठीक पाँच बजे प्रस्थान करती है।","leave, exit","arrive","departure = प्रस्थान।",2,"travel"],
    ["Guide","गाइड","मार्गदर्शक","noun","A local guide showed us the fort.","एक स्थानीय मार्गदर्शक ने हमें किला दिखाया।","escort, leader","","guide करना = मार्ग दिखाना।",2,"travel"],
    ["Tourist","टूरिस्ट","पर्यटक","noun","Tourists visit this lake in winter.","पर्यटक सर्दियों में इस झील पर आते हैं।","visitor, traveller","local","tourism = पर्यटन।",2,"travel"],
    ["Vehicle","व्हीकल","वाहन","noun","Park your vehicle outside.","अपना वाहन बाहर खड़ा करें।","transport, carrier","","उच्चारण वी-इकल है।",2,"travel"],
    ["Fare","फ़ेयर","किराया","noun","The bus fare has increased.","बस का किराया बढ़ गया है।","charge, rate","","fare = किराया, fair = मेला/उचित।",2,"travel"],
    ["Delay","डिले","देरी","noun","The train is running with a delay.","गाड़ी देरी से चल रही है।","holdup, lag","","delayed by two hours.",2,"travel"],
    ["Return","रिटर्न","वापस आना","verb","We return home on Sunday.","हम रविवार को घर लौटते हैं।","come back, restore","depart","return back दोहराव है।",1,"travel"],
    ["Direction","डायरेक्शन","दिशा","noun","Ask a shopkeeper for direction.","दिशा के लिए दुकानदार से पूछिए।","way, course","","in the direction of.",2,"travel"],
    ["Adventure","एडवेंचर","साहसिक कार्य","noun","The trek was a real adventure.","वह पैदल यात्रा सच्चा साहसिक कार्य थी।","expedition, thrill","boredom","adventurous = साहसी।",2,"travel"],

    /* ---- jobs ---- */
    ["Job","जॉब","नौकरी","noun","He got a job in the bank.","उसे बैंक में नौकरी मिली।","work, post","","get/lose a job.",1,"jobs"],
    ["Work","वर्क","काम करना","verb","I work six days a week.","मैं हफ़्ते में छह दिन काम करता हूँ।","labour, function","rest","work as + पद।",1,"jobs"],
    ["Salary","सैलरी","वेतन","noun","The salary is paid on the first.","वेतन पहली तारीख़ को मिलता है।","pay, wages","","monthly salary कहें।",1,"jobs"],
    ["Office","ऑफ़िस","कार्यालय","noun","The office opens at ten.","कार्यालय दस बजे खुलता है।","workplace, bureau","","at the office = दफ़्तर में।",1,"jobs"],
    ["Employee","एम्प्लॉई","कर्मचारी","noun","Every employee gets a uniform.","हर कर्मचारी को वर्दी मिलती है।","worker, staff","employer","उच्चारण एम्प्लॉ-ई है।",2,"jobs"],
    ["Employer","एम्प्लॉयर","नियोक्ता","noun","A good employer respects time.","अच्छा नियोक्ता समय का सम्मान करता है।","boss, hirer","employee","employ = नियुक्त करना।",2,"jobs"],
    ["Duty","ड्यूटी","कर्तव्य","noun","It is my duty to help.","मदद करना मेरा कर्तव्य है।","responsibility, task","","on duty / off duty.",1,"jobs"],
    ["Skill","स्किल","कौशल","noun","Typing is a useful skill.","टाइपिंग एक उपयोगी कौशल है।","ability, talent","","skilled = कुशल।",1,"jobs"],
    ["Experience","एक्सपीरियंस","अनुभव","noun","She has five years of experience.","उसके पास पाँच साल का अनुभव है।","practice, exposure","","experience in + क्षेत्र।",2,"jobs"],
    ["Recruitment","रिक्रूटमेंट","भर्ती","noun","The recruitment starts next month.","भर्ती अगले महीने शुरू होगी।","hiring, enrolment","","recruit = भर्ती करना।",2,"jobs"],
    ["Promotion","प्रमोशन","पदोन्नति","noun","He received a promotion this year.","उसे इस साल पदोन्नति मिली।","upgrade, advancement","demotion","get a promotion.",2,"jobs"],
    ["Resign","रिज़ाइन","इस्तीफ़ा देना","verb","She decided to resign politely.","उसने विनम्रता से इस्तीफ़ा देने का निर्णय लिया।","quit, step down","join","resign from + पद।",3,"jobs"],
    ["Apply","अप्लाई","आवेदन करना","verb","Apply for the post before Friday.","शुक्रवार से पहले पद के लिए आवेदन करें।","request, submit","","apply for + नौकरी।",1,"jobs"],
    ["Resume","रिज़्यूमे","बायोडाटा","noun","Keep your resume to one page.","अपना बायोडाटा एक पन्ने का रखें।","CV, biodata","","resume = फिर से शुरू करना भी।",2,"jobs"],
    ["Deadline","डेडलाइन","अंतिम तिथि","noun","The deadline is Monday morning.","अंतिम तिथि सोमवार सुबह है।","due date, time limit","","meet a deadline = समय पर पूरा करना।",2,"jobs"],
    ["Team","टीम","दल","noun","Our team finished the work early.","हमारे दल ने काम जल्दी पूरा किया।","group, crew","individual","team work = सामूहिक काम।",1,"jobs"],
    ["Task","टास्क","कार्य","noun","This task needs two people.","इस कार्य के लिए दो लोग चाहिए।","job, assignment","","complete a task.",1,"jobs"],
    ["Report","रिपोर्ट","विवरण देना","noun","Submit the report by evening.","शाम तक विवरण जमा करें।","account, record","","report to + अधिकारी।",2,"jobs"],
    ["Shift","शिफ़्ट","पाली","noun","I work in the night shift.","मैं रात की पाली में काम करता हूँ।","turn, duty period","","shift = बदलना भी होता है।",1,"jobs"],
    ["Overtime","ओवरटाइम","अतिरिक्त समय","noun","Overtime is paid double.","अतिरिक्त समय का दोगुना भुगतान होता है।","extra hours","","do overtime कहें।",2,"jobs"],
    ["Colleague","कॉलीग","सहकर्मी","noun","My colleague helped me a lot.","मेरे सहकर्मी ने बहुत मदद की।","co-worker, associate","","उच्चारण कॉ-लीग है।",2,"jobs"],
    ["Vacancy","वेकेंसी","रिक्ति","noun","There is one vacancy for a clerk.","क्लर्क के लिए एक रिक्ति है।","opening, post","","vacancy for + पद।",2,"jobs"],
    ["Appointment","अपॉइंटमेंट","नियुक्ति, मुलाक़ात","noun","I have an appointment at four.","मेरी चार बजे मुलाक़ात है।","meeting, posting","","fix an appointment.",2,"jobs"],
    ["Retire","रिटायर","सेवानिवृत्त होना","verb","My father will retire next year.","मेरे पिता अगले साल सेवानिवृत्त होंगे।","step down","join","retirement = सेवानिवृत्ति।",2,"jobs"],

    /* ---- motivation ---- */
    ["Motivation","मोटिवेशन","प्रेरणा","noun","Motivation comes from small wins.","प्रेरणा छोटी जीत से आती है।","drive, inspiration","laziness","motivate = प्रेरित करना।",2,"motivation"],
    ["Success","सक्सेस","सफलता","noun","Success needs patience and work.","सफलता के लिए धैर्य और मेहनत चाहिए।","achievement, victory","failure","successful = सफल।",1,"motivation"],
    ["Failure","फ़ेल्योर","असफलता","noun","Failure is only a lesson.","असफलता केवल एक सबक है।","defeat, setback","success","fail = असफल होना।",2,"motivation"],
    ["Effort","एफ़र्ट","प्रयास","noun","Your effort will never be wasted.","आपका प्रयास कभी व्यर्थ नहीं जाएगा।","attempt, labour","laziness","make an effort — do नहीं।",2,"motivation"],
    ["Goal","गोल","लक्ष्य","noun","Write your goal on paper.","अपना लक्ष्य काग़ज़ पर लिखिए।","aim, target","","set a goal = लक्ष्य तय करना।",1,"motivation"],
    ["Dream","ड्रीम","सपना","noun","Never stop chasing your dream.","अपने सपने का पीछा करना कभी मत छोड़िए।","vision, hope","","dream of / dream about.",1,"motivation"],
    ["Hope","होप","आशा","noun","Hope keeps a person moving.","आशा इंसान को चलते रहने देती है।","expectation, faith","despair","hope for the best.",1,"motivation"],
    ["Courage","करेज","साहस","noun","It takes courage to start again.","फिर से शुरू करने में साहस लगता है।","bravery, nerve","fear","courageous = साहसी।",2,"motivation"],
    ["Confidence","कॉन्फ़िडेंस","आत्मविश्वास","noun","Practice builds confidence.","अभ्यास आत्मविश्वास बनाता है।","self-belief, assurance","doubt","confident = आत्मविश्वासी।",2,"motivation"],
    ["Patience","पेशेंस","धैर्य","noun","Learning a language needs patience.","भाषा सीखने में धैर्य चाहिए।","tolerance, calm","impatience","patient = धैर्यवान और मरीज़।",2,"motivation"],
    ["Determination","डिटरमिनेशन","दृढ़ संकल्प","noun","Her determination changed everything.","उसके दृढ़ संकल्प ने सब बदल दिया।","resolve, will","weakness","determined = संकल्पित।",3,"motivation"],
    ["Believe","बिलीव","विश्वास करना","verb","Believe in your own effort.","अपने प्रयास पर विश्वास कीजिए।","trust, accept","doubt","believe in + व्यक्ति/बात।",1,"motivation"],
    ["Achieve","अचीव","हासिल करना","verb","You can achieve this in a year.","आप इसे एक साल में हासिल कर सकते हैं।","attain, reach","lose","achievement = उपलब्धि।",2,"motivation"],
    ["Struggle","स्ट्रगल","संघर्ष","noun","Every struggle teaches something.","हर संघर्ष कुछ सिखाता है।","fight, hardship","ease","struggle with / struggle for.",2,"motivation"],
    ["Progress","प्रोग्रेस","प्रगति","noun","Slow progress is still progress.","धीमी प्रगति भी प्रगति है।","advance, growth","decline","अगणनीय — progresses नहीं।",2,"motivation"],
    ["Improve","इम्प्रूव","सुधारना","verb","Improve a little every day.","हर दिन थोड़ा सुधार कीजिए।","better, enhance","worsen","improvement = सुधार।",1,"motivation"],
    ["Inspire","इंस्पायर","प्रेरित करना","verb","Your story can inspire others.","आपकी कहानी दूसरों को प्रेरित कर सकती है।","motivate, encourage","discourage","inspiration = प्रेरणा।",2,"motivation"],
    ["Positive","पॉज़िटिव","सकारात्मक","adjective","Keep a positive attitude daily.","रोज़ सकारात्मक दृष्टिकोण रखिए।","optimistic, hopeful","negative","positive thinking = सकारात्मक सोच।",1,"motivation"],
    ["Focus","फ़ोकस","ध्यान केंद्रित करना","verb","Focus on one word at a time.","एक बार में एक शब्द पर ध्यान दीजिए।","concentrate, aim","distract","focus on + विषय।",1,"motivation"],
    ["Consistency","कंसिस्टेंसी","निरंतरता","noun","Consistency beats talent.","निरंतरता प्रतिभा से आगे निकल जाती है।","regularity, steadiness","irregularity","consistent = लगातार।",3,"motivation"],
    ["Sacrifice","सैक्रिफ़ाइस","त्याग","noun","Every big goal asks for sacrifice.","हर बड़ा लक्ष्य त्याग माँगता है।","surrender, giving up","","sacrifice for + उद्देश्य।",3,"motivation"],
    ["Victory","विक्ट्री","विजय","noun","Victory belongs to the patient.","विजय धैर्यवान की होती है।","win, triumph","defeat","victorious = विजयी।",2,"motivation"],
    ["Challenge","चैलेंज","चुनौती","noun","Treat every problem as a challenge.","हर समस्या को चुनौती मानिए।","test, difficulty","","face a challenge = चुनौती का सामना।",2,"motivation"],
    ["Persist","परसिस्ट","डटे रहना","verb","Persist even when progress is slow.","प्रगति धीमी हो तब भी डटे रहिए।","continue, endure","quit","persistence = दृढ़ता।",3,"motivation"],

    /* ---- leadership ---- */
    ["Leader","लीडर","नेता","noun","A leader listens before speaking.","नेता बोलने से पहले सुनता है।","chief, head","follower","leadership = नेतृत्व।",1,"leadership"],
    ["Vision","विज़न","दूरदृष्टि","noun","A clear vision guides the team.","स्पष्ट दूरदृष्टि दल का मार्गदर्शन करती है।","foresight, insight","","vision = दृष्टि भी होती है।",2,"leadership"],
    ["Decision","डिसीज़न","निर्णय","noun","Take the decision without fear.","बिना डर के निर्णय लीजिए।","choice, judgement","doubt","make/take a decision.",1,"leadership"],
    ["Responsibility","रिस्पॉन्सिबिलिटी","ज़िम्मेदारी","noun","Leadership means responsibility.","नेतृत्व का अर्थ है ज़िम्मेदारी।","duty, charge","","take responsibility for.",2,"leadership"],
    ["Delegate","डेलिगेट","काम सौंपना","verb","A good leader knows how to delegate.","अच्छा नेता काम सौंपना जानता है।","assign, hand over","","delegate work to somebody.",3,"leadership"],
    ["Influence","इन्फ़्लुएंस","प्रभाव","noun","Her influence changed the village.","उसके प्रभाव ने गाँव बदल दिया।","impact, effect","","influence on / over.",2,"leadership"],
    ["Respect","रिस्पेक्ट","सम्मान","noun","Respect is earned, not demanded.","सम्मान कमाया जाता है, माँगा नहीं जाता।","honour, regard","insult","respect for + व्यक्ति।",1,"leadership"],
    ["Trust","ट्रस्ट","भरोसा","noun","Trust takes years to build.","भरोसा बनने में वर्षों लगते हैं।","faith, belief","distrust","trust in somebody.",1,"leadership"],
    ["Teamwork","टीमवर्क","सामूहिक कार्य","noun","Teamwork finishes work faster.","सामूहिक कार्य से काम जल्दी पूरा होता है।","cooperation","conflict","अगणनीय संज्ञा।",2,"leadership"],
    ["Manage","मैनेज","प्रबंध करना","verb","She manages twenty workers.","वह बीस मज़दूरों का प्रबंध करती है।","handle, run","","manager = प्रबंधक।",1,"leadership"],
    ["Motivate","मोटिवेट","उत्साह बढ़ाना","verb","Praise can motivate a whole team.","प्रशंसा पूरे दल को प्रेरित कर सकती है।","encourage, drive","discourage","motivate somebody to do.",2,"leadership"],
    ["Support","सपोर्ट","सहायता करना","verb","Support your team in bad times.","बुरे समय में अपने दल की सहायता कीजिए।","help, back","oppose","supportive = सहायक।",1,"leadership"],
    ["Initiative","इनिशिएटिव","पहल","noun","He took the initiative to start.","उसने शुरू करने की पहल की।","first step, drive","","take the initiative.",3,"leadership"],
    ["Accountable","अकाउंटेबल","जवाबदेह","adjective","A leader is accountable for results.","नेता परिणामों के लिए जवाबदेह होता है।","answerable, liable","","accountable to + व्यक्ति।",3,"leadership"],
    ["Mentor","मेंटर","मार्गदर्शक गुरु","noun","Find a mentor in your field.","अपने क्षेत्र में एक मार्गदर्शक गुरु खोजिए।","adviser, coach","","mentor करना = मार्गदर्शन देना।",2,"leadership"],
    ["Empower","एम्पावर","सशक्त बनाना","verb","Education empowers women.","शिक्षा महिलाओं को सशक्त बनाती है।","enable, strengthen","weaken","empowerment = सशक्तिकरण।",3,"leadership"],
    ["Fair","फ़ेयर","न्यायसंगत","adjective","Give everyone a fair chance.","सबको न्यायसंगत अवसर दीजिए।","just, equal","unfair","fair = मेला और गोरा भी।",1,"leadership"],
    ["Command","कमांड","आदेश, अधिकार","noun","She has good command over English.","उसकी अंग्रेज़ी पर अच्छी पकड़ है।","order, control","","command over + भाषा/विषय।",2,"leadership"],
    ["Example","एग्ज़ाम्पल","उदाहरण","noun","Lead by example, not by words.","शब्दों से नहीं, उदाहरण से नेतृत्व कीजिए।","instance, model","","for example = उदाहरण के लिए।",1,"leadership"],
    ["Unity","यूनिटी","एकता","noun","Unity makes a small team strong.","एकता छोटे दल को मज़बूत बनाती है।","togetherness, harmony","division","unite = एक होना।",2,"leadership"],

    /* ---- interview ---- */
    ["Interview","इंटरव्यू","साक्षात्कार","noun","My interview is on Monday.","मेरा साक्षात्कार सोमवार को है।","meeting, discussion","","attend/face an interview.",1,"interview"],
    ["Introduction","इंट्रोडक्शन","परिचय","noun","Start with a short introduction.","संक्षिप्त परिचय से शुरू कीजिए।","opening, preface","conclusion","self-introduction तैयार रखें।",2,"interview"],
    ["Weakness","वीकनेस","कमज़ोरी","noun","Name a weakness you are improving.","ऐसी कमज़ोरी बताइए जिसे आप सुधार रहे हैं।","fault, drawback","strength","weakness for = किसी चीज़ का शौक।",2,"interview"],
    ["Achievement","अचीवमेंट","उपलब्धि","noun","Share one achievement with proof.","एक उपलब्धि प्रमाण के साथ बताइए।","accomplishment, success","failure","greatest achievement पूछा जाता है।",2,"interview"],
    ["Qualification","क्वालिफ़िकेशन","योग्यता","noun","List your highest qualification first.","अपनी सर्वोच्च योग्यता पहले लिखिए।","credential, degree","","educational qualification.",2,"interview"],
    ["Candidate","कैंडिडेट","उम्मीदवार","noun","Ten candidates applied for the post.","पद के लिए दस उम्मीदवारों ने आवेदन किया।","applicant, aspirant","","candidate for + पद।",2,"interview"],
    ["Selection","सिलेक्शन","चयन","noun","The selection list came out today.","चयन सूची आज आई।","choice, pick","rejection","select = चुनना।",1,"interview"],
    ["Rejection","रिजेक्शन","अस्वीकृति","noun","One rejection is not the end.","एक अस्वीकृति अंत नहीं है।","refusal, denial","acceptance","reject = अस्वीकार करना।",2,"interview"],
    ["Punctual","पंक्चुअल","समय का पाबंद","adjective","Be punctual on the interview day.","साक्षात्कार के दिन समय के पाबंद रहिए।","on time, prompt","late","punctuality = समयनिष्ठा।",2,"interview"],
    ["Formal","फ़ॉर्मल","औपचारिक","adjective","Wear formal clothes for the interview.","साक्षात्कार के लिए औपचारिक कपड़े पहनिए।","official, proper","casual, informal","formal language = शिष्ट भाषा।",2,"interview"],
    ["Impression","इम्प्रेशन","छाप","noun","The first impression matters most.","पहली छाप सबसे अधिक मायने रखती है।","effect, image","","make a good impression.",2,"interview"],
    ["Prepare","प्रिपेयर","तैयारी करना","verb","Prepare five common questions.","पाँच सामान्य प्रश्नों की तैयारी कीजिए।","get ready, plan","","preparation = तैयारी।",1,"interview"],
    ["Expectation","एक्सपेक्टेशन","अपेक्षा","noun","What is your salary expectation?","आपकी वेतन अपेक्षा क्या है?","hope, demand","","expect = अपेक्षा करना।",2,"interview"],
    ["Reference","रेफ़रेंस","संदर्भ, सिफ़ारिश","noun","Add two references in the resume.","बायोडाटा में दो संदर्भ जोड़िए।","recommendation, source","","refer = संदर्भ देना।",2,"interview"],
    ["Offer","ऑफ़र","प्रस्ताव","noun","I received the offer letter today.","मुझे आज प्रस्ताव पत्र मिला।","proposal, bid","","offer letter = नियुक्ति पत्र।",1,"interview"],
    ["Notice","नोटिस","सूचना अवधि","noun","My notice period is one month.","मेरी सूचना अवधि एक महीने की है।","warning, information","","notice period पूछा जाता है।",2,"interview"],
    ["Probation","प्रोबेशन","परिवीक्षा","noun","The probation lasts six months.","परिवीक्षा छह महीने चलती है।","trial period","","on probation = परिवीक्षा पर।",3,"interview"],
    ["Panel","पैनल","चयन समिति","noun","A panel of three took the interview.","तीन सदस्यों की समिति ने साक्षात्कार लिया।","board, committee","","interview panel कहते हैं।",2,"interview"],
    ["Eligible","एलिजिबल","पात्र","adjective","Graduates are eligible for this post.","स्नातक इस पद के लिए पात्र हैं।","qualified, entitled","ineligible","eligible for + पद।",2,"interview"],
    ["Suitable","सूटेबल","उपयुक्त","adjective","This job is suitable for freshers.","यह नौकरी नए लोगों के लिए उपयुक्त है।","fitting, appropriate","unsuitable","suitable for + व्यक्ति।",2,"interview"],

    /* ---- personality ---- */
    ["Personality","पर्सनैलिटी","व्यक्तित्व","noun","A calm personality wins trust.","शांत व्यक्तित्व भरोसा जीतता है।","character, nature","","personality development = व्यक्तित्व विकास।",2,"personality"],
    ["Attitude","एटीट्यूड","दृष्टिकोण","noun","Your attitude decides your height.","आपका दृष्टिकोण आपकी ऊँचाई तय करता है।","outlook, mindset","","attitude towards + बात।",2,"personality"],
    ["Behaviour","बिहेवियर","व्यवहार","noun","Polite behaviour opens many doors.","विनम्र व्यवहार कई दरवाज़े खोलता है।","conduct, manner","","अमेरिकी वर्तनी: behavior.",2,"personality"],
    ["Honest","ऑनेस्ट","ईमानदार","adjective","Be honest even when it is hard.","कठिन हो तब भी ईमानदार रहिए।","truthful, sincere","dishonest","H मौन है — ऑनेस्ट बोलें।",1,"personality"],
    ["Humble","हंबल","विनम्र, नम्र","adjective","He stayed humble after success.","सफलता के बाद भी वह विनम्र रहा।","modest, simple","arrogant","humility = विनम्रता।",2,"personality"],
    ["Kind","काइंड","दयालु","adjective","Be kind to strangers too.","अजनबियों के प्रति भी दयालु रहिए।","gentle, caring","cruel","kindness = दयालुता।",1,"personality"],
    ["Generous","जेनरस","उदार","adjective","She is generous with her time.","वह अपने समय को लेकर उदार है।","giving, liberal","selfish","generosity = उदारता।",2,"personality"],
    ["Calm","काम","शांत","adjective","Stay calm during an argument.","बहस के दौरान शांत रहिए।","peaceful, quiet","angry","L मौन है — काम बोलें।",1,"personality"],
    ["Curious","क्यूरियस","जिज्ञासु","adjective","Curious people learn faster.","जिज्ञासु लोग तेज़ी से सीखते हैं।","inquisitive, eager","indifferent","curiosity = जिज्ञासा।",2,"personality"],
    ["Creative","क्रिएटिव","रचनात्मक","adjective","Creative thinking solves old problems.","रचनात्मक सोच पुरानी समस्याएँ हल करती है।","imaginative, original","dull","creativity = रचनात्मकता।",2,"personality"],
    ["Ambitious","एम्बिशियस","महत्वाकांक्षी","adjective","He is ambitious but patient.","वह महत्वाकांक्षी पर धैर्यवान है।","aspiring, driven","content","ambition = महत्वाकांक्षा।",3,"personality"],
    ["Loyal","लॉयल","वफ़ादार","adjective","A loyal friend stays in bad times.","वफ़ादार मित्र बुरे समय में साथ रहता है।","faithful, devoted","disloyal","loyalty = वफ़ादारी।",2,"personality"],
    ["Grateful","ग्रेटफ़ुल","आभारी","adjective","I am grateful for your help.","मैं आपकी मदद के लिए आभारी हूँ।","thankful, obliged","ungrateful","grateful to + व्यक्ति, for + चीज़।",2,"personality"],
    ["Optimistic","ऑप्टिमिस्टिक","आशावादी","adjective","Stay optimistic about your result.","अपने परिणाम को लेकर आशावादी रहिए।","hopeful, positive","pessimistic","optimism = आशावाद।",3,"personality"],
    ["Reliable","रिलायबल","भरोसेमंद","adjective","He is a reliable worker.","वह भरोसेमंद कर्मचारी है।","dependable, trusty","unreliable","rely on = भरोसा करना।",2,"personality"],
    ["Sincere","सिन्सियर","निष्ठावान","adjective","Give a sincere apology.","निष्ठापूर्वक क्षमा माँगिए।","genuine, honest","insincere","sincerity = निष्ठा।",2,"personality"],
    ["Empathy","एम्पैथी","समानुभूति","noun","Empathy makes you a better listener.","समानुभूति आपको बेहतर श्रोता बनाती है।","compassion, understanding","indifference","empathy = महसूस करना, sympathy = तरस।",3,"personality"],
    ["Charisma","करिश्मा","आकर्षक व्यक्तित्व","noun","His charisma fills the room.","उसका आकर्षक व्यक्तित्व पूरे कमरे में छा जाता है।","charm, appeal","","charismatic = आकर्षक।",3,"personality"]
  ];

  HEM.WORDS = ROWS.map(function (r, i) {
    return {
      id: i, en: r[0], pron: r[1], hi: r[2], pos: r[3], sent: r[4],
      sentHi: r[5], syn: r[6], ant: r[7], tip: r[8], level: r[9], cat: r[10]
    };
  });

  HEM.CATEGORIES = [
    { key:"all", en:"All Words", hi:"सभी शब्द", icon:"◆" },
    { key:"daily", en:"Daily Life", hi:"रोज़मर्रा", icon:"☀" },
    { key:"education", en:"Education", hi:"शिक्षा", icon:"✎" },
    { key:"business", en:"Business", hi:"व्यापार", icon:"₹" },
    { key:"tech", en:"Technology", hi:"तकनीक", icon:"⌘" },
    { key:"ai", en:"AI", hi:"कृत्रिम बुद्धि", icon:"◉" },
    { key:"comm", en:"Communication", hi:"संवाद", icon:"✉" },
    { key:"health", en:"Health", hi:"स्वास्थ्य", icon:"✚" },
    { key:"travel", en:"Travel", hi:"यात्रा", icon:"✈" },
    { key:"jobs", en:"Jobs", hi:"नौकरी", icon:"▤" },
    { key:"motivation", en:"Motivation", hi:"प्रेरणा", icon:"★" },
    { key:"leadership", en:"Leadership", hi:"नेतृत्व", icon:"⚑" },
    { key:"interview", en:"Interview", hi:"साक्षात्कार", icon:"◎" },
    { key:"personality", en:"Personality", hi:"व्यक्तित्व", icon:"❖" }
  ];

  HEM.LEVEL_NAME = { 1: "Easy \u00b7 \u0906\u0938\u093e\u0928", 2: "Medium \u00b7 \u092e\u0927\u094d\u092f\u092e", 3: "Hard \u00b7 \u0915\u0920\u093f\u0928" };

  /* Each test receives a plain stats object from store.stats() — no globals. */
  HEM.ACHIEVEMENTS = [
    { id:"first",    icon:"\ud83c\udf31", en:"First Step",        hi:"\u092a\u0939\u0932\u093e \u0915\u0926\u092e",           desc:"Answer your first word",             test:function(s){ return s.answers >= 1; } },
    { id:"ten",      icon:"\ud83d\udcd8", en:"Ten Down",          hi:"\u0926\u0938 \u092a\u0942\u0930\u0947",                   desc:"Learn 10 words correctly",           test:function(s){ return s.learned >= 10; } },
    { id:"fifty",    icon:"\ud83d\udcda", en:"Half Century",      hi:"\u0905\u0930\u094d\u0927\u0936\u0924\u0915",             desc:"Learn 50 words correctly",           test:function(s){ return s.learned >= 50; } },
    { id:"hundred",  icon:"\ud83c\udfc6", en:"Century Maker",     hi:"\u0936\u0924\u0915\u0935\u0940\u0930",                     desc:"Learn 100 words correctly",          test:function(s){ return s.learned >= 100; } },
    { id:"streak3",  icon:"\ud83d\udd25", en:"Three Day Fire",    hi:"\u0924\u0940\u0928 \u0926\u093f\u0928 \u0915\u0940 \u0932\u094c", desc:"Practise 3 days in a row",      test:function(s){ return s.bestStreak >= 3; } },
    { id:"streak7",  icon:"\u26a1", en:"Week Warrior",             hi:"\u0938\u092a\u094d\u0924\u093e\u0939 \u092f\u094b\u0926\u094d\u0927\u093e", desc:"Practise 7 days in a row", test:function(s){ return s.bestStreak >= 7; } },
    { id:"sharp",    icon:"\ud83c\udfaf", en:"Sharp Shooter",     hi:"\u0905\u091a\u0942\u0915 \u0928\u093f\u0936\u093e\u0928\u093e", desc:"80% accuracy over 50 answers", test:function(s){ return s.answers >= 50 && s.accuracy >= 80; } },
    { id:"speller",  icon:"\u270d", en:"Spell Master",             hi:"\u0935\u0930\u094d\u0924\u0928\u0940 \u0917\u0941\u0930\u0941", desc:"Win 20 spell challenges",      test:function(s){ return s.spellWins >= 20; } },
    { id:"speaker",  icon:"\ud83c\udfa4", en:"Brave Speaker",     hi:"\u0928\u093f\u0921\u0930 \u0935\u0915\u094d\u0924\u093e", desc:"Finish 15 pronunciation checks", test:function(s){ return s.speakTries >= 15; } },
    { id:"daily5",   icon:"\ud83d\udcc5", en:"Daily Regular",     hi:"\u0928\u093f\u092f\u092e\u093f\u0924 \u0936\u093f\u0937\u094d\u092f", desc:"Finish 5 Daily Challenges", test:function(s){ return s.dailyDone >= 5; } },
    { id:"level5",   icon:"\ud83d\udc51", en:"Level Five",        hi:"\u092a\u093e\u0901\u091a\u0935\u093e\u0901 \u0938\u094d\u0924\u0930", desc:"Reach Level 5",             test:function(s){ return s.level >= 5; } },
    { id:"explorer", icon:"\ud83e\udded", en:"Category Explorer", hi:"\u0936\u094d\u0930\u0947\u0923\u0940 \u0916\u094b\u091c\u0940", desc:"Practise 6 categories",      test:function(s){ return s.catCount >= 6; } }
  ];
})(window.HEM = window.HEM || {});
